version: 2.1
orbs:
  go: gotest/tools@0.0.9


jobs:
  mod-tidy-check:
    executor: go/circleci-golang
    steps:
      - go/install-ssh
      - checkout
      - go/mod-tidy-check

workflows:
  version: 2
  ci:
    jobs:
      - go/lint
      - go/test:
          executor: go/circleci-golang
      - mod-tidy-check
